### ISSUE TITLE
embed proj-sys crate in proj repo?

### ISSUE THREAD

**Issue by michaelkirk** [georust/proj-sys#26]
It's pretty common to track a sys-crate and it's higher level bindings in a single repo.

e.g.

- https://github.com/sfackler/rust-openssl
- https://github.com/servo/core-foundation-rs
- https://github.com/georust/gdal

It's one less repo to manage and it makes it a little easier to ensure we don't break the api - e.g. we can avoid the situation where proj-sys tests pass, but proj tests using that proj-sys break.

In practice I end up doing something like this locally anyway, by modifying my local proj to use my local proj-sys, but to me it seems a little more convenient if they share a repo. And we can confer that benefit to anyone else opening a PR.

Additionally, the projects can share ci config, issue trackers, etc.

**Comment by michaelkirk** [comment]
To clarify - I'm proposing we get rid of this repository, and convert https://github.com/georust/proj to a workspace which includes both the `proj` and `proj-sys` crates.

**Comment by rmanoka** [comment]
Good idea; makes sense to me.
