### ISSUE TITLE
Project fails to build: fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by Maximkaaa** [georust/proj-sys#7]
I've cloned the repo, but running `cargo build` on it produces the following output:
```
   Compiling proj-sys v0.12.2 (/home/maxim/dev/rust/proj-sys)
error: failed to run custom build command for `proj-sys v0.12.2 (/home/maxim/dev/rust/proj-sys)`

Caused by:
  process didn't exit successfully: `/home/maxim/dev/rust/proj-sys/target/debug/build/proj-sys-b67742c1a5915ba3/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=proj
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
/usr/local/include/proj.h:120:10: fatal error: 'stddef.h' file not found
/usr/local/include/proj.h:120:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I'm not very familiar with the C build chains, but it seems that the stdlib header files are not located where the build system expects to find them.

My system:
* Linux Mint 19.1 Cinnamon
* gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
* libclang-dev: 1:6.0-41~exp5~ubuntu1

I would be happy to give more details if needed.

**Comment by urschrei** [comment]
This might be related to clang (but I'm not an expert), and the fix is that you need to install the actual clang package(s) – see https://github.com/rust-lang/rust-bindgen/issues/242#issuecomment-275229404. Either way, this doesn't look like a specific `proj-sys` error, so if the above doesn't work you'll get more help on one of the main Discord channels.

**Comment by Maximkaaa** [comment]
So, after more searching and trying, the solution was trivial. Installing `clang` package does the deal. So, on Debian derived systems (Ubuntu, Mint) it is:

    sudo apt-get install clang

Probably, it can be a good idea to mention the dependency somewhere in the docs or readme. If you want, I can make a PR.
